package com.example.morsefree;

public enum MorseLevel {
    NULL_LEVEL , E_AND_T_LEVEL,
    I_AND_M_LEVEL, A_AND_N_LEVEL,
    S_AND_O_LEVEL, U_AND_G_LEVEL,
    R_AND_K_LEVEL, W_AND_D_LEVEL,
    H_AND_SH_LEVEL, V_AND_CH_LEVEL,
    F_AND_Q_LEVEL, YU_AND_Z_LEVEL,
    L_AND_Y_LEVEL, YA_AND_C_LEVEL,
    P_AND_X_LEVEL, J_AND_B_LEVEL,
    HARD_SING_LEVEL, ONE_AND_SIX_LEVEL,
    TWO_AND_SEVEN_LEVEL, THREE_AND_EIGHT_LEVEL,
    FOUR_AND_NINE_LEVEL, FIVE_AND_ZERO_LEVEL,
    OPEN_BRACKET_AND_CLOSE_BRACKET_LEVEL,
    POINT_AND_COMMA_LEVEL, SEMICOLON_AND_COLON_LEVEL,
    QUOTES_AND_APOSTROPHE_LEVEL, DASH_AND_SLASH_LEVEL,
    QUESTION_LEVEL_AND_EXCLAMATION_MARK_LEVEL,
    AT_LEVEL
}
