package com.example.morsefree;

import static com.example.morsefree.MorseLevel.*;

public enum MorseLevel {
    MORSE_LEVEL_NULL, MORSE_LEVEL_E_AND_T,
    MORSE_LEVEL_I_AND_M, MORSE_LEVEL_A_AND_N,
    MORSE_LEVEL_S_AND_O, MORSE_LEVEL_U_AND_G,
    MORSE_LEVEL_R_AND_K, MORSE_LEVEL_W_AND_D,
    MORSE_LEVEL_H_AND_SH, MORSE_LEVEL_V_AND_CH,
    MORSE_LEVEL_F_AND_Q, MORSE_LEVEL_YU_AND_Z,
    MORSE_LEVEL_L_AND_Y, MORSE_LEVEL_YA_AND_C,
    MORSE_LEVEL_P_AND_X, MORSE_LEVEL_J_AND_B,
    MORSE_LEVEL_HARD_SING, MORSE_LEVEL_ONE_AND_SIX,
    MORSE_LEVEL_TWO_AND_SEVEN, MORSE_LEVEL_THREE_AND_EIGHT,
    MORSE_LEVEL_FOUR_AND_NINE, MORSE_LEVEL_FIVE_AND_ZERO,
    MORSE_LEVEL_OPEN_BRACKET_AND_CLOSE_BRACKET,
    MORSE_LEVEL_POINT_AND_COMMA,
    MORSE_LEVEL_SEMICOLON_AND_COLON,
    MORSE_LEVEL_QUOTES_AND_APOSTROPHE,
    MORSE_LEVEL_DASH_AND_SLASH,
    MORSE_LEVEL_QUESTION_MARK_AND_EXCLAMATION_MARK,
    MORSE_LEVEL_AT
}
